esphome:
  name: dsmr
  friendly_name: DSMR Reader
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    #type: esp-idf
    type: arduino

logger:
  level: ERROR

mqtt:
  broker: !secret mqtt_broker

ota:
  - platform: esphome
    password: ""

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dsmr Fallback Hotspot"
    password: "12345678"

captive_portal:

uart:
  id: uart_bus
  rx_pin:
    number: GPIO10
    inverted: true
  baud_rate: 115200
  rx_buffer_size: 1700

output:
  - platform: gpio
    pin: GPIO8
    id: status
    inverted: true

light:
  - platform: status_led
    name: Status LED
    output: status

dsmr:
  id: dsmr_instance
  max_telegram_length: 1700

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    update_interval: 300s
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    icon: mdi:clock-outline
    entity_category: "diagnostic"

  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
    gas_delivered_be:
      name: "Gas Consumed Belgium"
    active_energy_import_current_average_demand:
      name: "Peak Current Average Quarterly Demand"
      icon: mdi:chart-sankey
    active_energy_import_maximum_demand_running_month:
      name: "Peak Month Maximum Quarterly Demand"
      icon: mdi:chart-sankey
    active_energy_import_maximum_demand_last_13_months:
      name: "Peak 13 Month Maximum Quarterly Demand"
      icon: mdi:chart-sankey

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version_be:
      name: "DSMR Version Belgium"
    electricity_tariff:
      name: "DSMR Tariff"
    message_long:
      name: "DSMR Message Long"
      icon: mdi:message-text-outline
  - platform: wifi_info
    ip_address:
      name: "DSMR IP Address"
    ssid:
      name: "DSMR Wi-Fi SSID"
    bssid:
      name: "DSMR Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
