- alias: Turn on outdoor lights at dusk
  trigger:
    platform: sun
    event: sunset
    offset: '-00:10:00'
  condition:
    condition: time
    before: '22:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_auto

- alias: Turn off outdoor lights at night
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_auto

- alias: Turn on indoor lights at dusk
  trigger:
    platform: sun
    event: sunset
    offset: '-00:10:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_auto

- alias: Turn off outdoor lights at sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:10:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.indoor_auto

- alias: Turn on outdoor lights in the morning
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: sun
    before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_auto

- alias: Turn off outdoor lights at sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:10:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_auto

- alias: Turn on garden lights at dusk
  trigger:
    platform: sun
    event: sunset
    offset: '-00:10:00'
  condition:
    condition: template
    # from April to end of October
    value_template: "{{ now().month in range(4, 11) }}"
  action:
    service: homeassistant.turn_on
    entity_id: group.garden_auto

- alias: Turn off garden lights at night
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.garden_auto

- alias: Turn on TV light when digicorder is turned on
  trigger:
    platform: state
    entity_id: device_tracker.digicorder
    to: 'home'
  condition:
    condition: sun
    after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: light.living_tv

- alias: Turn on TV light at dusk if digicorder is on
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: device_tracker.digicorder
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_tv

- alias: Turn off TV light when digicorder is turned off
  trigger:
    platform: state
    entity_id: device_tracker.digicorder
    to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id: light.living_tv

- alias: Turn off bed lights in the morning during the week
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_off
    entity_id: group.bed_lights

- alias: Turn off bed lights in the morning during the weekend
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: homeassistant.turn_off
    entity_id: group.bed_lights

- alias: Turn on bed lights in the evening
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.bed_lights

- alias: Open curtains in the morning
  trigger:
    platform: time
    at: '10:30:00'
  action:
    service: cover.open_cover
    entity_id: cover.bedroom_both_curtain

- alias: Close curtains at dusk
  trigger:
    platform: sun
    event: sunset
    offset: '00:30:00'
  action:
    service: cover.close_cover
    entity_id: cover.bedroom_both_curtain

- alias: Turn off heating at night
  trigger:
    platform: time
    at: "22:00:00"
  condition:
    condition: state
    entity_id: climate.heating
    state: 'heat'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.heating
        preset_mode: 'eco'

- alias: Automatically turn off light after 30 mins
  trigger:
    - platform: state
      entity_id:
        - light.bathroom_mirror
        - light.bathroom_ceiling
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  action:
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

  # holiday automation
- alias: Holiday - Turn on entrance light at dusk
  trigger:
    platform: sun
    event: sunset
    offset: '00:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'on'
    - condition: time
      before: '22:50:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.entrance_wall

- alias: Holiday - Turn off entrance light at night
  trigger:
    platform: time
    at: '22:50:00'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.entrance_wall

- alias: Holiday - Turn on dinner light at dusk
  trigger:
    platform: sun
    event: sunset
    offset: '00:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'on'
    - condition: time
      before: '23:0:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.dinner_table

- alias: Holiday - Turn off dinner light at night
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.dinner_table

- alias: Holiday - Turn on night hall light at 22:40
  trigger:
    platform: time
    at: '22:40:00'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.night_hall

- alias: Holiday - Turn off night hall light at 23:10
  trigger:
    platform: time
    at: '23:10:00'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.night_hall

- alias: Shoot purple nerf
  trigger:
    platform: state
    entity_id: sensor.ir_code
    to: '0x67228B44'
  action:
    - service: homeassistant.toggle
      entity_id: light.sibe_ceiling
    - service: mqtt.publish
      data:
        topic: 'tele/sonoff-ir/RESULT'
        payload: '{"IrReceived":{"Protocol":"UNKNOWN","Bits":0,"Data":"0"}}'

- alias: Shoot red nerf
  trigger:
    platform: state
    entity_id: sensor.ir_code
    to: '0x78653B0E'
  action:
    - service: homeassistant.toggle
      entity_id: light.sibe_bed
    - service: mqtt.publish
      data:
        topic: 'tele/sonoff-ir/RESULT'
        payload: '{"IrReceived":{"Protocol":"UNKNOWN","Bits":0,"Data":"0"}}'

- alias: Shoot blue nerf
  trigger:
    platform: state
    entity_id: sensor.ir_code
    to: '0x2FFEA610'
  action:
    - service: homeassistant.toggle
      entity_id: light.sibe_bed_led
    - service: mqtt.publish
      data:
        topic: 'tele/sonoff-ir/RESULT'
        payload: '{"IrReceived":{"Protocol":"UNKNOWN","Bits":0,"Data":"0"}}'
