entrance:
  name: Entrance
  entities:
    - light.entrance_wall
    - light.stairs_wall
    - light.dinner_table
    - light.terras
    - light.switch_3_s20_3
    - switch.blitzwolf_shp13

kitchen:
  name: Kitchen
  entities:
    - light.kitchen_closets
    - light.kitchen_cooking
    - light.kitchen_table
    - light.kitchen_wall

living:
  name: Living
  entities:
    - light.living_couch
    - light.living_lone
    - light.living_office
    - light.living_tv
    - light.living_rgb_bulb
    - light.living_led_pillar

office:
  name: Office
  entities:
    - light.office

nighthall:
  name: Night hall
  entities:
    - light.night_hall
    - fan.upstairs_fan

sibe:
  name: sibe
  entities:
    - light.sibe_bed
    - light.sibe_bed_led
    - light.sibe_ceiling

lone:
  name: Lone
  entities:
    - light.lone_bed
    - light.lone_bed_led
    - light.lone_ceiling

bed_lights:
  name: Bedlights
  entities:
    - light.sibe_bed_led
    - light.lone_bed_led

bathroom:
  name: Bathroom
  entities:
    - light.bathroom_mirror
    - light.bathroom_ceiling

bedroom:
  name: Bedroom
  entities:
    - light.evelyne_bed
    - light.peter_bed
    - light.bedroom_wall
    - light.stars_1
    - light.stars_2
    - light.stars_3
    - light.stars_4
    - light.stars_5

outdoor:
  name: Outdoor
  entities:
    - light.front_door
    - light.switch_1_s20_1
    - light.switch_2_s20_2
    - light.switch_3_s20_3
    - light.back_downstairs
    - light.back_upstairs
    - light.pool
    - light.garden

outdoor-auto:
  name: Outdoor Automation
  entities:
    - light.front_door
    - light.switch_1_s20_1
    - light.switch_2_s20_2
    - light.terras

indoor-auto:
  name: Indoor Automation
  entities:
    - light.stairs
    - light.bathroom_leds

garden-auto:
  name: Garden Automation
  entities:
    - light.pool
    - light.garden

guestroom:
  name: Guestroom
  entities:
    - light.guest_room

downstairs-auto-off:
  name: Downstairs automation all-off
  entities:
    - light.switch_2_s20_2
    - light.living_tv
    - light.living_rgb_bulb
    - light.terras

upstairs-auto-off:
  name: Upstairs automation all-off
  entities:
    - light.stars_1
    - light.stars_2
    - light.stars_3
    - light.stars_4
    - light.stars_5

christmas-auto:
  name: Christmas lights automation
  entities:
    - light.switch_3_s20_3
    - light.blitzwolf2_switch
    - light.blitzwolf3_switch
    - light.sonsock4_switch

downstairs:
  name: Downstairs
  entities:
    - group.entrance
    - group.kitchen
    - group.living
    - group.office

upstairs:
  name: Upstairs
  entities:
    - group.nighthall
    - group.sibe
    - group.lone
    - group.bathroom
    - group.bedroom
    - group.guestroom

family:
  name: Family
  entities:
    - person.peter
    - person.evelyne
    - person.lone
    - person.sibe

parents:
  name: Parents
  entities:
    - person.peter
    - person.evelyne
